---

name: Module release

on:
  repository_dispatch:
    types: [remote_release_trigger]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        type: string
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  github-release:
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ github.event.client_payload.version || github.event.inputs.version }}
      publish: true
